apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-service
  namespace: vidio
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::202197228322:role/vidio-dev-video-service"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processing-service
  namespace: vidio
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::202197228322:role/vidio-dev-processing-service"
