spring:
  application:
    name: processing-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8089/realms/vidio/protocol/openid-connect/certs}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/video_platform_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: processing-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.mddev.processingservice.event
        spring.json.use.type.headers: false
      auto-offset-reset: earliest

server:
  port: 8083

kafka:
  topics:
    video-uploaded: video.uploaded
    processing-completed: video.processing.completed
    processing-failed: video.processing.failed

storage:
  s3:
    endpoint: ${S3_ENDPOINT:}
    region: ${S3_REGION:us-east-1}
    bucket: ${S3_BUCKET:vidio-videos}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
    path-style-access: ${S3_PATH_STYLE_ACCESS:true}
